# Generated by Django 3.0.3 on 2021-01-29 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_address', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=8)),
                ('country', models.CharField(choices=[('I', 'INDIA'), ('P', 'PAKISTAN'), ('B', 'Bangladesh')], max_length=20)),
                ('address_type', models.CharField(choices=[('S', 'Shipping'), ('B', 'Billing')], max_length=1)),
                ('default', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_type', models.CharField(blank=True, max_length=20, null=True)),
                ('cloth_brand', models.CharField(blank=True, max_length=15, null=True)),
                ('wear_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes_Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_size', models.CharField(blank=True, choices=[('L', 'Large'), ('M', 'Medium'), ('O', 'Other'), ('S', 'Small'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large'), ('XXXL', 'Extra Extra Extra Large')], max_length=4, null=True)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('model_name', models.CharField(blank=True, max_length=20, null=True)),
                ('laptop_brand', models.CharField(blank=True, choices=[('A', 'Asus'), ('AC', 'Acer'), ('AP', 'Apple'), ('D', 'Dell'), ('H', 'HP'), ('L', 'Lenovo'), ('S', 'Sony')], max_length=2, null=True)),
                ('screen_height', models.CharField(blank=True, max_length=4, null=True)),
                ('screen_width', models.CharField(blank=True, max_length=4, null=True)),
                ('screen_type', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.FloatField()),
                ('processor_brand', models.CharField(blank=True, max_length=10, null=True)),
                ('processor_speed', models.IntegerField()),
                ('processor_type', models.CharField(blank=True, max_length=10, null=True)),
                ('resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('ram', models.IntegerField()),
                ('storage_type', models.CharField(blank=True, choices=[('H', 'HDD'), ('S', 'SDD')], max_length=1, null=True)),
                ('storage_size', models.IntegerField()),
                ('graphics_card_detail', models.CharField(blank=True, max_length=20, null=True)),
                ('graphics_card_size', models.IntegerField()),
                ('battery_details', models.CharField(blank=True, max_length=30, null=True)),
                ('max_memory_supported', models.IntegerField()),
                ('usb_port', models.IntegerField()),
                ('drive_type', models.CharField(blank=True, max_length=10, null=True)),
                ('hardware_interface', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('model_name', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_brand', models.CharField(blank=True, choices=[('A', 'Apple'), ('B', 'Black Berry'), ('L', 'Lava'), ('M', 'Motorola'), ('MI', 'RedMi'), ('N', 'Nokia'), ('O', 'Oppo'), ('OP', 'One Plus'), ('S', 'Sony'), ('SS', 'Samsung'), ('V', 'Vivo')], max_length=2, null=True)),
                ('screen_height', models.CharField(blank=True, max_length=4, null=True)),
                ('screen_width', models.CharField(blank=True, max_length=4, null=True)),
                ('screen_type', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.FloatField()),
                ('processor', models.CharField(blank=True, max_length=10, null=True)),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
                ('front_camera_number', models.IntegerField()),
                ('back_camera_number', models.IntegerField()),
                ('camera_details', models.CharField(blank=True, max_length=10, null=True)),
                ('box_detail', models.CharField(blank=True, max_length=30, null=True)),
                ('battery_power', models.IntegerField()),
                ('special', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('packer', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes_Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(null=True)),
                ('count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_brand', models.CharField(blank=True, choices=[('F', 'Fastrack'), ('R', 'Rado'), ('RL', 'Rolex'), ('S', 'Sonata'), ('T', 'Titan'), ('TH', 'Tag Heure')], max_length=2, null=True)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_brand', models.CharField(choices=[('A', 'Adidas'), ('AS', 'Asics'), ('F', 'Fila'), ('L', 'Lotto'), ('N', 'Nike'), ('NB', 'New Balance'), ('P', 'Puma'), ('R', 'Reebok')], max_length=2)),
                ('shoe_type', models.CharField(choices=[('Fo', 'Formal'), ('L', 'Loafer'), ('R', 'Running'), ('Sn', 'Sneakers'), ('Sp', 'Sports')], max_length=2)),
                ('shoes_size', models.ManyToManyField(to='E_app.Shoes_Size')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image0', models.ImageField(upload_to='file/')),
                ('image1', models.ImageField(upload_to='file/')),
                ('image2', models.ImageField(blank=True, upload_to='file/')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_color', models.CharField(max_length=10)),
                ('product_gender', models.CharField(choices=[('K', 'Kids'), ('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=1)),
                ('product_type', models.CharField(choices=[('C', 'Clothes'), ('L', 'Laptop'), ('M', 'Mobile'), ('S', 'Shoes'), ('W', 'Watch')], max_length=2)),
                ('product_details', models.CharField(max_length=1000)),
                ('product_deal_week', models.BooleanField(default=False)),
                ('product_deal_month', models.BooleanField(default=False)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('deal_price', models.FloatField(blank=True, null=True)),
                ('discount', models.IntegerField(default=10)),
                ('clothe_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='E_app.Clothes')),
                ('laptop_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='E_app.Laptop')),
                ('mobile_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='E_app.Mobile')),
                ('shoes_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='E_app.Shoes')),
                ('watch_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='E_app.Watches')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('ordered', models.BooleanField(default=False)),
                ('product_quantity', models.IntegerField(default=1)),
                ('order_size', models.IntegerField()),
                ('canceled', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_app.Product_Detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('order_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('being_delivered', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='E_app.Address')),
                ('items', models.ManyToManyField(to='E_app.OrderItem')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='E_app.Payment')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='E_app.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(blank=True, max_length=10)),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=10)),
                ('addresses', models.ManyToManyField(to='E_app.Address')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='cloth_size',
            field=models.ManyToManyField(to='E_app.Clothes_Size'),
        ),
    ]
