# Generated by Django 3.0.3 on 2021-01-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='product_gender',
        ),
        migrations.AddField(
            model_name='clothes',
            name='product_gender',
            field=models.CharField(choices=[('K', 'Kids'), ('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoes',
            name='product_gender',
            field=models.CharField(choices=[('K', 'Kids'), ('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watches',
            name='product_gender',
            field=models.CharField(choices=[('K', 'Kids'), ('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
