# Generated by Django 3.0.3 on 2021-01-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_app', '0002_auto_20210129_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='screen_height',
            new_name='screen_size',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='screen_height',
            new_name='screen_size',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='drive_type',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='graphics_card_size',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='screen_width',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='screen_width',
        ),
        migrations.AddField(
            model_name='laptop',
            name='connector_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='graphics_card_interface',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='graphics_card_ram_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='graphics_coprocessor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='hard_drive_interface',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='hard_drive_rotation_speed',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='model_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='operating_system',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='optical_drive_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='power_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='connectivity_technology',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='dimensions',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='display_technology',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='operating_system',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='wireless_communication',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='hardware_interface',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='max_memory_supported',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor_speed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='screen_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage_size',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='box_detail',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='camera_details',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='special',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
