# Generated by Django 3.0.3 on 2021-01-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_app', '0003_auto_20210129_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
