# Generated by Django 3.0.3 on 2021-01-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_app', '0004_auto_20210129_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
