# Generated by Django 3.0.3 on 2021-01-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_app', '0006_auto_20210129_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='watch_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
