# Generated by Django 3.0.3 on 2021-01-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_app', '0007_auto_20210129_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes_size',
            old_name='cloth_size',
            new_name='size',
        ),
    ]
